import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import I18nProvider from '@/components/configurations/i18n-provider';  // Importa el provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProvider>  {/* Envuelve todo con el provider */}
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}